[package]
name = "lazyide"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.4"
notify = "6"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tui-textarea = { version = "0.7", features = ["search"] }
url = "2"

[dev-dependencies]
tempfile = "3"
